#caller workflow and called workflow can reside in same repo or different repo

name: Reusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "All"
        required: false

    secrets:
      access-token:
        description: "Secret description"
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    #which repo is checked out (caller or called?)
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      # which context is shown (caller or called?)
      - name: Display github context
        run: echo '${{ toJSON(github) }}'
      - name: Display name input
        run: echo ${{ inputs.name }}
      - name: Display access-token-secret
        run: echo ${{ secrets.access-token }}
